#ifndef __COMPONENTS_H__
#define __COMPONENTS_H__

#include "Entity.hpp"

#include "AirQuality.hpp"
#include "AlarmControlPanel.hpp"
#include "Alert.hpp"
#include "Automation.hpp"
#include "BinarySensor.hpp"
#include "Calendar.hpp"
#include "Camera.hpp"
#include "Climate.hpp"
#include "Counter.hpp"
#include "Cover.hpp"
#include "DeviceTracker.hpp"
#include "Fan.hpp"
#include "Group.hpp"
#include "Humidifier.hpp"
#include "InputBoolean.hpp"
#include "InputDateTime.hpp"
#include "InputNumber.hpp"
#include "InputSelect.hpp"
#include "InputText.hpp"
#include "Light.hpp"
#include "Lock.hpp"
#include "MediaPlayer.hpp"
#include "Person.hpp"
#include "Plant.hpp"
#include "Proximity.hpp"
#include "Remote.hpp"
#include "Scene.hpp"
#include "Script.hpp"
#include "Sensor.hpp"
#include "Sun.hpp"
#include "Switch.hpp"
#include "Timer.hpp"
#include "Updater.hpp"
#include "Vacuum.hpp"
#include "WaterHeater.hpp"
#include "Weather.hpp"
#include "Zone.hpp"

#endif // __COMPONENTS_H__